- name: timezone
  command: echo "Asia/Tokyo" > /etc/timezone
  sudo: true
  tags: common

- name: Install packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items: essentialpkg
  tags: common
